### ISSUE TITLE
Remove "this" in result of nameof.full

### ISSUE THREAD

**Issue by Kukks** [dsherret/ts-nameof#11]
It's far easier to be able to do the following when using `nameof` in the same class. It's also impossible to reference private properties when referring interfaces
```
class Test{
  private x:Test;
  public y: Test;
  public z: string;

nameof(this.x) // "x"
nameof(this.x.y) // "y"
nameof.full(this.x.y.z) "x.y.z"
}
```

**Comment by Kukks** [comment]
My bad, the this context work but I still can't use the `full` with it

**Comment by dsherret** [comment]
Hi @Kukks, I just [committed](https://github.com/dsherret/ts-nameof/commit/93626f5010fa375b36512c38838d594b50ba060a) a passing test to this issue. Can you take a look at it? (11-source.txt is the input and 11-expected.txt is the expected output)

Is that output what you would expect? If not, can you provide what you think the output should be? Or maybe I got the scenario wrong? Thanks!

Perhaps you are expecting the output of `nameof.full(this.x.y.z)` to be `"x.y.z"` instead of `"this.x.y.z"`? I think there's an argument to be made there... it's not very useful to know "this". I want to tread carefully when making a change like this, but it's an obscure scenario. I'll increase the major revision. Do you agree with making that change?

**Comment by Kukks** [comment]
@dsherret I would expect it to be "x.y.z" since `this` is only used to refer to the current context. there is no way to output a private nested member in a class otherwise(without `this.`).

Perhaps an optional param for `full` would be better if you think it should remain as is. 

My use-case for this is for Aurelia and it's `@computedFrom` decorator and also the `BindingEngine.propertyObserver` functionality where you only need the name of the property("x", "x.y", "x.y.z") 

For now, I am using a template string as you had in the closed issue before the implementation of `full`
:)

**Comment by dsherret** [comment]
I'm thinking about something like this:

```typescript
nameof.full(obj: name, startIndex?: number);
```

Examples:

```typescript
nameof.full(this.x.y.z) // "this.x.y.z"
nameof.full(this.x.y.z, 0) // "this.x.y.z"
nameof.full(this.x.y.z, 1) // "x.y.z"
nameof.full(this.x.y.z, 2) // "y.z"
nameof.full(this.x.y.z, 3) // "z"
nameof.full(this.x.y.z, 4) // build error
nameof.full(this.x.y.z, -1) // "z"
nameof.full(this.x.y.z, -2) // "y.z"
nameof.full(this.x.y.z, -3) // "x.y.z"
nameof.full(this.x.y.z, -4) // "this.x.y.z"
nameof.full(this.x.y.z, -5) // build error
```

What do you think?

**Comment by Kukks** [comment]
That would be sufficient and beyond! 👍

**Comment by dsherret** [comment]
@Kukks cool. Thanks for spurring this idea and for your feedback! I like this addition and it being backwards compatible is a plus.

I'll implement this over the weekend. I'm closing this in favour of #12.

**Comment by dsherret** [comment]
@Kukks this is in version 0.8. Let me know if you have any issues.
