### ISSUE TITLE
nameof type generics

### ISSUE THREAD

**Issue by ondratra** [dsherret/ts-nameof#31]
This code currently returns "T" as result. 
```
function myFunc<T>() {
    console.log(nameof<T>())
}
myFunc<String>()
```

Can we create new feature to `nameof` that could return name of type passed to generic function? (`String` in example provided)

**Comment by dsherret** [comment]
@ondratra what should the output code be if someone does this?

```ts
function myFunc<T>() {
    console.log(nameof<T>())
}
myFunc<string>()
myFunc<number>()
```

**Comment by ondratra** [comment]
Good point. It probably can't be achieved.

**Comment by leolorenzoluis** [comment]
@dsherret I expect the output to be string and number? Will adding a constraint on T such as classes only will help on determining what the output should be? I'm not sure what TypeScript gives you in order to determine the nameof.

**Comment by dsherret** [comment]
@leolorenzoluis I'm not sure how a constraint would help. How should this code look once it's transformed (how should it look as JavaScript code)?

```ts
function myFunc<T extends { name: string; }>() {
    console.log(nameof<T>());
}

myFunc<Person>();
myFunc<Dog>();
myFunc<Cat>();
```

The only way I see is to transform it as this:

```ts
function myFunc(nameofTypeArg) {
    console.log(nameofTypeArg);
}

myFunc("Person");
myFunc("Dog");
myFunc("Cat");
```

But that is just asking for trouble.

**Comment by leolorenzoluis** [comment]
Thanks for your response. You definitely know more about the TypeScript world than me. I would imagine if TypeScript offers you a way to actually constraint it within a class like in C#, so you can use the constructor.name when you're transforming? However, that means I can't do types now but have to use value types. 

In theory I would expect something like this
```
function myFunc<T extends ClassA>() {
    console.log(nameof<T>());
}

myFunc<Person>();
myFunc<Dog>();
myFunc<Cat>();
```

However the transformations defeats the purpose of the nameof and now requires value types and it might be iffy due to how the compiler works and will end up like this

```
function myFunc(value) {
    console.log(value.constructor.name);
}
const person = new Person();
myFunc(person);
```

**Comment by dsherret** [comment]
@leolorenzoluis what you're describing seems more like a `typeof(T).Name` in c#. In c#, `nameof(T)` would be `"T"` so I think the behaviour here is correct as well.

Regardless, if there were a `typeof<T>()` or something transform, it would need to be able to pass the type at the call site (since `T` is not around once compiled to JavaScript). So `myFunc<Person>()` would change to `myFunc(personType)`. That's basically impossible to do unless the code being run won't ever be called by other code that's not being compiled.

**Comment by leolorenzoluis** [comment]
Right. However if ts-nameof is already doing transformations what would be the reason why it can't pass/"hack" in a "string" of that T when transpiled to Javascript? So myFunc<Person> can be myFunc("Person")? I understand TypeScript is constrained with the JS specs unlike C# that they have the full authority for the design.

**Comment by dsherret** [comment]
@leolorenzoluis if a `typeof<T>()` transform were to be implemented—not `nameof`—then the transform would have to change the function header to accept this and work appropriately. For example:

```ts
function myFunc<T>(param1: string, ...params: T[]) {
    console.log(typeof<T>.Name);
}

myFunc("test", "other", "final");
```

Could be transformed to:

```ts
function myFunc(tType, param1, ...params) {
    console.log(tType.Name);
}

myFunc(typeProvider.getType("string"), "test", "other", "final");

// or

function myFunc(param1, params, tType) {
    console.log(tType.Name);
}

myFunc("test", ["other", "final"], typeProvider.getType("string"));
```

...and this would also need to update the `arguments` value.

That's a problem if that code is being called from a different location (ex. adding a `typeof<T>` within a method on the public API would change the function header and potentially cause problems for callers of that public API).

**Comment by leolorenzoluis** [comment]
What if there's another lib based on ts-nameof that can accept those side effects? I think it's useful for a lot of stuff where I don't care about the caller of the API and I know what the side effects will be if it's used improperly. However, abstracting these kind of stuff to other callers of the public API is useful for an enterprise team. What do you think?

**Comment by ondratra** [comment]
@leolorenzoluis I think original post of @dsherret illustrate the problem well. Imho there is no way to accomplish what you are asking. 

@leolorenzoluis You said you would expect `number` and `string` as results of original example, but if I create extended example you will see that it couldn't be decided what will be nameof T.

```
function myNestedFunc<T>() {
    console.log(nameof<T>())
}
function myFunc<U>() {
    myNestedFunc<U>()
}
myFunc<string>()
myFunc<number>()
```
Even if we change current behaviour it could in then return `string/number` or `U` (and both would make sense in some situations).

You should probably find another design pattern to solve your problem.

**Comment by dsherret** [comment]
@leolorenzoluis I think this could be done, but feel like it's more trouble to do than it's worth and can't think of why it would be useful over a runtime solution. If someone were to implement this `typeof` function would probably need to compile the code with the compiler API in order to get the types passed in at call sites and then use that information in the transform while emitting.

I agree with @ondratra that a different design pattern would probably be better. It won't lock all your code into needing to use it, which could make migration away from it difficult in the future.
