### ISSUE TITLE
Confused about the setup

### ISSUE THREAD

**Issue by farzadmf** [dsherret/ts-nameof#38]
Hi,

I was so happy to find out that this package existed, but when I tried to use it, I was so confused.

Am I missing something? I'm asking because the setup seems too complicated. Can it not be just a normal `import nameof from 'ts-nameof'` and then use it?

**Comment by dsherret** [comment]
Hey @farzadmf,

It's not possible to simply import this library and start using it because the `nameof` operation needs to happen at compile time rather than runtime. For example, if you have an interface or type called `Person`, there's no easy way to get that at runtime because the type information goes away once compiled (in other words... `nameof<Person>()` compiles to `Person`, but the only way to get `Person` is at compile time).

Also, you're right that the setup is not straightforward and I'm sorry about that... I wish it was easier. The reason is that there is no standard way to inject AST transformers into the compilation process. Hopefully that will come in time once the TypeScript compiler team standardizes this... please upvote this issue on TypeScript's issue tracker in the meantime: https://github.com/Microsoft/TypeScript/issues/14419

For an ok runtime solution for getting property names of objects or types, you could use something like this:

```ts
function nameof<T>(key: keyof T): string;
function nameof<T>(object: T, key: keyof T): string;
function nameof(objectOrKey: string | any, key?: string) {
    return key || objectOrKey;
}

// example use
interface Person {
    name: string;
}
const person: Person = { name: "" };
console.log(nameof(person, "name"));
console.log(nameof<Person>("name"));
```

...but that unfortunately doesn't have all the capabilities of `ts-nameof`.

**Comment by farzadmf** [comment]
Thank you @dsherret for the quick reply :) What you said about compile time makes sense, so I think I can close this, and see what happens in future
